image: docker:git

stages:
  - deploy

deploy_ui_to_staging:
  stage: deploy
  environment: Development
  services:
       - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.com:5005
    - docker build -t registry.gitlab.com/reallybigtree/pinecone-wordpress-destination .
    - docker push registry.gitlab.com/reallybigtree/pinecone-wordpress-destination
  only:
    - develop
